pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: '--filter Category=Unit'

- task: AzurePowerShell@4
  displayName: 'Reset Azure services for integration tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'Reset.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: -ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name)

- task: AzurePowerShell@4
  displayName: 'Prepare configuration values for integration tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'ConfigureTestLocalSettings.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: -ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name) -SourceRootDir $(Build.Repository.LocalPath)

- task: DotNetCoreCLI@2
  displayName: 'Run integration tests'
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: --blame-hang-timeout=30m --filter Category=Integration

- task: AzurePowerShell@4
  displayName: 'Reset Azure services for functional tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'Reset.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: -ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name)