pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: '--filter Category=Unit'

- task: AzurePowerShell@4
  displayName: 'Reset Azure services for integration tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'Reset.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: -ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name) -UseLocalEmulatorSettings

- task: AzurePowerShell@4
  displayName: 'Prepare configuration values for integration tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'ConfigureTestLocalSettings.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: -ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name) -SourceRootDir $(Build.Repository.LocalPath) -UseLocalEmulatorSettings

- task: DotNetCoreCLI@2
  displayName: Run integration tests
  timeoutInMinutes: 5
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: --blame --verbosity normal --filter Category=Integration

- task: AzurePowerShell@4
  displayName: 'Reset Azure services for functional tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'Reset.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: -ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name) -UseLocalEmulatorSettings

- task: PowerShell@2
  name: config_version
  displayName: Configure release version
  inputs:
    targetType: filePath
    filePath: 'ConfigureVersion.ps1'
    arguments: -BuildConfiguration Release -IncrementVersionType minor

- task: DotNetCoreCLI@2
  displayName: Build Example Solution
  inputs:
    command: build
    projects: 'Examples\Eklee.Azure.Functions.GraphQl.Example\Eklee.Azure.Functions.GraphQl.Example.csproj'
    arguments: --configuration=$(config_version.buildConfig) -p:Version=$(config_version.version)

- task: PowerShell@2
  name: prep_example
  displayName: Prepare npm dependencies to run Example Solution
  inputs:
    targetType: filePath
    filePath: 'PrepExample.ps1'
    arguments: -Path $(Build.SourcesDirectory) -BuildConfig $(config_version.buildConfig)