pool:
  vmImage: 'windows-latest'

steps:

- task: AzurePowerShell@4
  displayName: 'Prepare configuration values tests'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'ConfigureTestLocalSettings.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: '-ResourceGroupName $(Global.ResourceGroupName) -Name $(Global.Name) -SourceRootDir $(Build.Repository.LocalPath)'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: '--filter Category=Unit'

- task: AzurePowerShell@4
  displayName: 'Reset Search'
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'FilePath'
    scriptPath: 'ResetSearch.ps1'
    azurePowerShellVersion: 'latestVersion'
    scriptArguments: '-ResourceGroupName $(Global.ResourceGroupName) -ServiceName $(Global.Name)'

- task: PowerShell@2
  displayName: 'Initialize Local Emulators'
  inputs:
    targetType: 'filePath'
    filePath: 'InitLocalEmulators.ps1'

- task: DotNetCoreCLI@2
  displayName: 'Run integration tests'
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: '--filter Category=Integration'